#!/bin/sh
#alpine-backup installer
#(C) Copyright 2009-2012 Nicholas Paun. All Rights Reserved.

INSTALLDIR="/alpine-backup" #Directory to copy all files to (if selected

BINDIR="/usr/sbin" #Directory to copy code
LIBDIR="/usr/lib/alpine-backup/" #Directory to copy mount drivers, etc.
CONFDIR="/etc/alpine-backup/" #Directory to copy configuration files

### THE MAGIC SED DETECTOR ###
case $(sed --help 2>&1) in
	  *GNU*) alias _sed='sed -i' ;;
	    *) alias _sed='sed -i ""' ;;
esac

if [ "$1" == "-h" ]; then
 echo "alpine-backup installer (for version 0.62)"
 echo "(C) Copyright 2009-2012 Nicholas Paun. All Rights Reserved."
 echo "Usage: $0 for normal install or $0 -d <directory> to install in directory"
 exit 0
fi

which php > /dev/null
if [ $? != 0 ]; then
 echo "PHP not found. Exiting."
 exit 1
fi

which rsync > /dev/null
if [ $? != 0 ]; then
 echo "rsync not found. Exiting."
 exit 1
fi

if [ "$1" == "-d" ]; then
 if [ "$2" != "" ]; then
  INSTALLDIR="$2" #Allow user to choose installdir
 fi
 rsync -av ./ $INSTALLDIR
 _sed -e s_/etc/alpine-backup/_$INSTALLDIR/conf/_gI  $INSTALLDIR/alpine-backup $INSTALLDIR/utils/* #Edit code to match installdir
 _sed -e s_/usr/lib/alpine-backup/_$INSTALLDIR/lib/_gI  $INSTALLDIR/alpine-backup
 _sed -e s_/var/log/alpine-backup/_$INSTALLDIR/data/_gI $INSTALLDIR/utils/* #Get all the utillities on the right track, too.

 _sed  -e s_" ago"__gI $INSTALLDIR/conf/* #### CORRECTS OLD DELETE_AFTER VALUES (prevents deletion of all backups)
else
 rsync -av ./*alp* $BINDIR
 rsync -av ./lib/ $LIBDIR
 rsync -av ./conf/ $CONFDIR

 _sed -e s_" ago"__gI $CONFDIR/* #### CORRECTS OLD DELETE_AFTER VALUES (prevents deletion of all backups)
fi
