#!/bin/bash
#alpine-backup installer
#(C) Copyright 2009-2011 Nicholas Paun. All Rights Reserved.

INSTALLDIR="/alpine-backup" #Directory to copy all files to (if set)

BINDIR="/usr/sbin" #Directory to copy code
LIBDIR="/usr/lib/alpine-backup/" #Directory to copy mount drivers, etc.
CONFDIR="/etc/alpine-backup/" #Directory to copy configuration files

which php &> /dev/null
if [[ $? != 0 ]]; then
 echo "PHP not found. Exiting."
 exit 1
fi

which rsync &> /dev/null
if [[ $? != 0 ]]; then
 echo "rsync not found. Exiting."
 exit 1
fi

if [[ $1 = "-d" ]]; then
 if [[ $2 != "" ]]; then
  INSTALLDIR="$2" #Allow user to choose installdir
 fi
 rsync -av ./ $INSTALLDIR
else
 rsync -av ./ $BINDIR
 rsync -av ./lib/ $LIBDIR
 rsync -av ./conf/ $CONFDIR
fi

exit 0
